### ISSUE TITLE
Support recent (2022) format .SAFE

### ISSUE THREAD

**Issue by marujore** [marujore/sentinel_angle_bands#15]
Similar to Issue  #9 
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

**Comment by TomKenda** [comment]
The error come from the `get_detfootprint(XML_File)` in the `s2_sensor_angs.py` file. 

In this function, the `qifname` is extracted from the metadata and then parsed  (` tree2 = ET.parse(foot[1])`).

In the former version of the L1C `MTD_TL.xml` file, the `qifname` was similar to this : 

`type="MSK_DETFOO">GRANULE/L1C_T31UFS_A028891_20210102T104435/QI_DATA/MSK_DETFOO_B01.gml</MASK_FILENAME>`

In the new version, this qi file is now in a .jp2 file : 

`type="MSK_DETFOO">GRANULE/L1C_T31UFS_A032495_20230527T103641/QI_DATA/MSK_DETFOO_B01.jp2</MASK_FILENAME>`

This difference in the metadata is causing the error. 

Does someone have an idea on how to fix this ? How to get the band footprints with the new version of metadata files ? Or is there a way to bypass this step to get the view and sun angle rasters ? Or another library doing the job for more recent images ?

Thanks in advance.

**Comment by TomKenda** [comment]
I gess that somehow we could modify the code in the following way : 

```
    bandfoot = []
    for foot in footprints:
        bandId = int(foot[0])
        if foot[0].endswith('.gml'):
            tree2 = ET.parse(foot[1])
            root2 = tree2.getroot()
            for child in root2:

                  ... [ reste of the code to parse the gml] ...

        elif foot[0].endswith('.jp2'):
                with rasterio.open(qifname) as src:
                    mask = src.read(1)
                    transform = src.transform
                detfootprint = mask_to_poly(mask, transform)
                ?...?
```

but I am not sur how to handle it afterwards

**Comment by marujore** [comment]
Hi @TomKenda , sorry for the late response.
Thank you for the PR, I will verify it in the next days.

**Comment by marujore** [comment]
Close on #16
